### ISSUE TITLE
Can't login with GitHub to signup for Doclets

### ISSUE THREAD

**Issue by kensnyder** [lipp/doclets#147]
I'm trying to login and try Doclets. I get to the GitHub authorization screen but when I click authorize I'm redirected to https://doclets.io/auth/github/callback?code=%hexstring%

And get the following error:
```
TypeError: req.session.save is not a function
   at Routes.authGithubCallback (/usr/src/app/lib/routes.js:15:15)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
   at complete (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:250:13)
   at /usr/src/app/node_modules/passport/lib/middleware/authenticate.js:257:15
   at pass (/usr/src/app/node_modules/passport/lib/authenticator.js:421:14)
   at Authenticator.transformAuthInfo (/usr/src/app/node_modules/passport/lib/authenticator.js:443:5)
   at /usr/src/app/node_modules/passport/lib/middleware/authenticate.js:254:22
   at /usr/src/app/node_modules/passport/lib/http/request.js:60:7
   at pass (/usr/src/app/node_modules/passport/lib/authenticator.js:267:43)
   at serialized (/usr/src/app/node_modules/passport/lib/authenticator.js:276:7)
   at /usr/src/app/lib/routes.js:394:9
   at model.<anonymous> (/usr/src/app/node_modules/mongoose/lib/document.js:1842:20)
   at next_ (/usr/src/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:89:34)
   at fnWrapper (/usr/src/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
   at /usr/src/app/node_modules/mongoose/lib/model.js:292:13
```

**Comment by jniles** [comment]
This also affects returning users who are trying to sign back in with github.

**Comment by lipp** [comment]
thanks for reporting! digging into this...

**Comment by lipp** [comment]
@jniles @kensnyder could you please re-try logging in/out to see if this still happens? thanks

**Comment by lipp** [comment]
... seems like some ressource/memory problem with session store....

**Comment by jniles** [comment]
@lipp, I am able to log in again.  Thanks!

**Comment by lipp** [comment]
i'll keep this issue open as I don't understand what was going wrong ...

**Comment by uedsky** [comment]
I have the same problem.
I've tried log out & in , reauthorize from github, it's still not work, please help!

**Comment by lipp** [comment]
@uedsky signup/login is working again. i have to resize my server vm, ... it seems to be a memory issue. sorry for the inconvenience & trouble.

**Comment by uedsky** [comment]
Another problem, I've pushed a repo named `docletstest`, but doclets cannot detect it, even after clicked the `re-sync respositories` btn

**Comment by lipp** [comment]
that's interesting.... many projects have been added during the last day... 
i will look into the logs...

**Comment by uedsky** [comment]
It appear now, maybe i'm just didn't see it. coz you guys use "reponame/username" form in repo list.

**Comment by lipp** [comment]
this was a misconfigured redis / docker host issue

**Comment by kensnyder** [comment]
Thank you, it is working for me as well.
