### ISSUE TITLE
Login-Issues, session can't be saved

### ISSUE THREAD

**Issue by Idrinth** [lipp/doclets#337]
There seems to be an issue with the session-handling at the moment when trying to log in:
```
TypeError: req.session.save is not a function
   at Routes.authGithubCallback (/usr/src/app/lib/routes.js:15:15)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
   at complete (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:250:13)
   at /usr/src/app/node_modules/passport/lib/middleware/authenticate.js:257:15
   at pass (/usr/src/app/node_modules/passport/lib/authenticator.js:421:14)
   at Authenticator.transformAuthInfo (/usr/src/app/node_modules/passport/lib/authenticator.js:443:5)
   at /usr/src/app/node_modules/passport/lib/middleware/authenticate.js:254:22
   at /usr/src/app/node_modules/passport/lib/http/request.js:60:7
   at pass (/usr/src/app/node_modules/passport/lib/authenticator.js:267:43)
   at serialized (/usr/src/app/node_modules/passport/lib/authenticator.js:276:7)
   at /usr/src/app/lib/routes.js:394:9
   at model.<anonymous> (/usr/src/app/node_modules/mongoose/lib/document.js:1913:20)
   at next_ (/usr/src/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:89:34)
   at fnWrapper (/usr/src/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
   at /usr/src/app/node_modules/mongoose/lib/model.js:3361:16
```
With the following on reload:
```
InternalOAuthError: Failed to fetch user profile
   at /usr/src/app/node_modules/passport-github2/lib/strategy.js:96:19
   at passBackControl (/usr/src/app/node_modules/passport-github2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/usr/src/app/node_modules/passport-github2/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:905:12)
   at nextTickCallbackWith2Args (node.js:441:9)
   at process._tickCallback (node.js:355:17)
```

**Comment by CamiloTD** [comment]
Happened to me too, site is useless for now

**Comment by jidemobell** [comment]
Just experienced this issue. req.session.save is not a function

**Comment by fewieden** [comment]
@lipp any update on that issue?

**Comment by yunnysunny** [comment]
I met the same problem now!

**Comment by magicznyleszek** [comment]
@lipp any plans to fix this? Doclets is broken for a year now.

**Comment by nico1996it** [comment]
@lipp same problem here...

**Comment by cherryblossom000** [comment]
@lipp I also have the same problem.
