### ISSUE TITLE
error while generating doc

### ISSUE THREAD

**Issue by mtrevisan** [lipp/doclets#55]
I have added my repository to doclets (https://github.com/mtrevisan/library), added the .doclets.yml accordingly (https://github.com/mtrevisan/library/blob/dev/.doclets.yml), and then it landed me to this page: https://doclets.io/mtrevisan/library/dev, giving me the following error:

`TypeError: /usr/src/app/views/doclayout.jade:19
   17| ul.args
   18| if func.params
   19| each param in _.filter(func.params, function(param) {return param.name.indexOf('.') === -1;})
   20| li(class=param.optional ? 'optional' : undefined)= param.name
   21| if !isCtor && func.returns && func.returns[0] && func.returns[0].type
   22| - var names = _.map(func.returns[0].type.names, tools.shortName);

Cannot read property 'indexOf' of undefined
   at eval (eval at <anonymous> (/usr/src/app/node_modules/jade/lib/index.js:218:8), <anonymous>:1645:71)
   at /usr/src/app/node_modules/underscore/underscore.js:227:11
   at Function._.each._.forEach (/usr/src/app/node_modules/underscore/underscore.js:153:9)
   at Function._.filter._.select (/usr/src/app/node_modules/underscore/underscore.js:226:7)
   at Object.eval (eval at <anonymous> (/usr/src/app/node_modules/jade/lib/index.js:218:8), <anonymous>:1645:17)
   at Object.jade_mixins.funcdeclx.jade_interp [as funcdeclx] (eval at <anonymous> (/usr/src/app/node_modules/jade/lib/index.js:218:8), <anonymous>:1677:4)
   at Object.jade_mixins.title.jade_interp [as title] (eval at <anonymous> (/usr/src/app/node_modules/jade/lib/index.js:218:8), <anonymous>:3654:25)
   at Object.jade_mixins.doclet.jade_interp [as doclet] (eval at <anonymous> (/usr/src/app/node_modules/jade/lib/index.js:218:8), <anonymous>:4468:21)
   at eval (eval at <anonymous> (/usr/src/app/node_modules/jade/lib/index.js:218:8), <anonymous>:4574:22)
   at eval (eval at <anonymous> (/usr/src/app/node_modules/jade/lib/index.js:218:8), <anonymous>:4599:4)
   at eval (eval at <anonymous> (/usr/src/app/node_modules/jade/lib/index.js:218:8), <anonymous>:4760:22)
   at res (/usr/src/app/node_modules/jade/lib/index.js:219:38)
   at Object.exports.renderFile (/usr/src/app/node_modules/jade/lib/index.js:380:38)
   at Object.exports.renderFile (/usr/src/app/node_modules/jade/lib/index.js:370:21)
   at View.exports.__express [as engine] (/usr/src/app/node_modules/jade/lib/index.js:417:11)
   at View.render (/usr/src/app/node_modules/express/lib/view.js:126:8)`

**Comment by lipp** [comment]
@mtrevisan thanks for reporting. there is definitely something weired going on... sorry for that. will look into it ....
